### ISSUE TITLE
Small Feature Request - Alternate Keyboard Layout Support

### ISSUE THREAD

**Issue by 641i130** [RobertElderSoftware/robert-elder-software-java-modules#2]
Just a small feature request that isn't very important, but I thought I'd list it anyways because I'm curious how you'll respond to it. 

It'd be cool to have support for alternate keyboard layouts, I use the Dvorak layout and my keyboard is hard coded to this layout meaning my computer still things I'm in qwerty. If there was an option to change layouts in the settings of the game, that would be pretty nifty!

**Comment by RobertElder** [comment]
That's fairly doable, I do recall that someone else requested this feature in the past as well on Kickstarter (perhaps it was you).  Now that I have the improved argument parsing, it should be that much work to add.  I'll add it to my to-do list.

**Comment by RobertElder** [comment]
Added in

9fb615ea45449cc01d00c6b68f36b4e1fdf5a383

**Comment by Stan-Stani** [comment]
I appreciate this because I prefer `asdf` for horizontal movement.
